# Generated by Django 5.1.7 on 2025-03-18 17:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0002_alter_shipmentorder_total_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='shop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='erp.shop', verbose_name='所属店铺'),
        ),
        migrations.AddField(
            model_name='product',
            name='stock_arrived',
            field=models.IntegerField(default=0, verbose_name='到岸数量'),
        ),
        migrations.AddField(
            model_name='product',
            name='stock_in_transit',
            field=models.IntegerField(default=0, verbose_name='在途数量'),
        ),
        migrations.AddField(
            model_name='product',
            name='stock_in_warehouse',
            field=models.IntegerField(default=0, verbose_name='在库数量'),
        ),
        migrations.AddField(
            model_name='product',
            name='value_arrived',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='到岸货值'),
        ),
        migrations.AddField(
            model_name='product',
            name='value_in_transit',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='在途货值'),
        ),
        migrations.AddField(
            model_name='product',
            name='value_in_warehouse',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='在库货值'),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock',
            field=models.IntegerField(default=0, verbose_name='总库存'),
        ),
    ]
