# Generated by Django 4.2.17 on 2024-12-26 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("erp", "0004_product_brand_product_created_at_product_dimensions_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="dimensions",
            new_name="volume",
        ),
        migrations.RemoveField(
            model_name="product",
            name="available",
        ),
    ]
