# Generated by Django 4.2.17 on 2024-12-28 08:17

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("erp", "0005_rename_dimensions_product_volume_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PackingList",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("total_boxes", models.IntegerField()),
                ("total_weight", models.DecimalField(decimal_places=2, max_digits=10)),
                ("total_volume", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "total_side_plus_one_volume",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("total_items", models.IntegerField()),
                ("type", models.CharField(max_length=100)),
                ("total_price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="PackingListItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.IntegerField()),
                (
                    "packing_list",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="erp.packinglist",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="erp.product"
                    ),
                ),
            ],
        ),
    ]
