# Generated by Django 5.1.7 on 2025-03-14 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0006_packinglist_packinglistitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='product',
            name='description',
        ),
        migrations.RemoveField(
            model_name='product',
            name='name',
        ),
        migrations.RemoveField(
            model_name='product',
            name='spu',
        ),
        migrations.RemoveField(
            model_name='product',
            name='status',
        ),
        migrations.RemoveField(
            model_name='product',
            name='supplier',
        ),
    ]
